### ISSUE TITLE
How the experimental.pth performs?

### ISSUE THREAD

**Issue by nihui** [BurguerJohn/Dain-App#1]
hi, thanks for your code sharing!

I found that there is experimental.pth model weight in your repo, I wonder how this new model performs.

Does it produce better visual experience?
Is this model trained on special datasets?

**Comment by BurguerJohn** [comment]
Hi Nihui.
Experimental was already a option in the latest few builds.
It usually produce worse results for real-live footage, but it can sometimes produce less artifacts on animations.
You could also interpolate the two models to try different results.
