### ISSUE TITLE
DAIN output FPS

### ISSUE THREAD

**Issue by 042lej** [BurguerJohn/Dain-App#22]
Inputted 832x1080 video into DAIN at flat 30.0FPS and set to interpolate at 2x.

Expected output - 60.0FPS
Actual output - 59.974FPS

Is there any way to set it to output at true 60.0FPS? I'm trying to splice audio from the original 30.0FPS video in, but the output video is a different length.

**Comment by turbodiesel4598** [comment]
@042lej Could I ask why you closed this issue? I'm interpolating 60 frames at 15 FPS to 60 FPS (4x), and for some reason I'm getting out 236 frames at 59 FPS.
