### ISSUE TITLE
无法运行：UnboundLocalError: local variable 'images' referenced before assignment

### ISSUE THREAD

**Issue by NULL204** [BurguerJohn/Dain-App#9]
![屏幕截图 2021-01-02 103927](https://user-images.githubusercontent.com/69097698/103449717-4db81c80-4ce7-11eb-8ca7-e18125ce1d22.png)
![屏幕截图 2021-01-02 103939](https://user-images.githubusercontent.com/69097698/103449718-4f81e000-4ce7-11eb-8dea-606e4b43f720.png)
![屏幕截图 2021-01-02 103954](https://user-images.githubusercontent.com/69097698/103449719-514ba380-4ce7-11eb-8a03-454649a875c0.png)
![屏幕截图 2021-01-02 104247](https://user-images.githubusercontent.com/69097698/103449721-527cd080-4ce7-11eb-9b65-42e48cb79284.png)

**Comment by YiWeiHuang-stack** [comment]
543876723

**Comment by BurguerJohn** [comment]
Can you please try renaming the .mp4 file to only contain american characters? I'm trying to check if this is what causing the bug.

**Comment by NULL204** [comment]
我想问一下，[Not Working]是什么导致的？
I want to ask, what is the cause of [Not Working]?

**Comment by YiWeiHuang-stack** [comment]
你换英文路径试试

**Comment by YiWeiHuang-stack** [comment]
你换成纯英文路径了么

**Comment by NULL204** [comment]
是全英文路径，我换了

**Comment by NULL204** [comment]
> 你换成纯英语路径了么

是的

**Comment by YiWeiHuang-stack** [comment]
能给个截图么

**Comment by NULL204** [comment]
> 能给个截图么

![image](https://user-images.githubusercontent.com/69097698/105491191-e5aa9400-5cf0-11eb-887b-b3f07e22881c.png)

**Comment by NULL204** [comment]
> 能给个截图么

![image](https://user-images.githubusercontent.com/69097698/105491248-fce98180-5cf0-11eb-8921-e139eb581b3f.png)

**Comment by YiWeiHuang-stack** [comment]
这不是正常拆图片呢么

**Comment by YiWeiHuang-stack** [comment]
QQ方便么，1315176066
